---
cloudProvider: vps
repo: docker-registry-service.example.com/
imageTag: latest
imagePullPolicy: Always
certsecretName: ca-key-pair
installKeel: true
domain: example.internal
ingressTLS: true

services:
  ## Functional Services

  login-api:
    typeDeployment: true
    resources: {}
    imageSource: sith-api
    replicaCount: 1
    command: ["bash", "-c", "update-ca-certificates --fresh && npm run setup && yarn start"]
    deploymentAnnotations: {}
    podAnnotations:
      co.elastic.logs/enabled: false
    livenessProbe:
      httpGet:
        path: /status
        port: 10010
      initialDelaySeconds: 5
      periodSeconds: 8
    servicePort:
      service: 10010
    service:
      enabled: true
      serviceType: ClusterIP
      serviceAnnotations: {}
      ports:
      - name: http
        protocol: TCP
        port: 10010
        targetPort: 10010
    ingress:
      servicePort: 10010
      enabled: false
      annotations: {}
      path: /
      host: api

  frontend-app:
    typeDeployment: true
    resources: {}
    imageSource: juicer-web-ui
    replicaCount: 1
    command: ["bash", "-c", "update-ca-certificates --fresh && npm start"]
    deploymentAnnotations: {}
    podAnnotations:
      co.elastic.logs/enabled: false
    servicePort:
      service: 3000
    service:
      enabled: true
      serviceType: ClusterIP
      serviceAnnotations: {}
      ports:
      - name: http
        protocol: TCP
        port: 3000
        targetPort: 3000
    ingress:
      enabled: false
